events {}
http {
    server {
        listen 80;

        # Отдаем статику фронтенда
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Скрытый канал для агентов (Остается без изменений)
        location /cdn/assets/v2/metrics.json {
            proxy_pass http://control_api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # REST API для дашборда
        location /api/ {
            proxy_pass http://control_api:8000;
            proxy_set_header Host $host;
        }

        # WebSocket для реалтайм ленты событий
        location /ws/ {
            proxy_pass http://control_api:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}