events {}
http {
    server {
        listen 80;
        
        # Скрытый канал для агентов
        location /cdn/assets/v2/metrics.json {
            proxy_pass http://control_api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Открытый API для дашборда оператора
        location /api/ {
            proxy_pass http://control_api:8000;
            proxy_set_header Host $host;
        }
    }
}